scan
	base-package:com.chuan.simple.bean.example.basic.bean.aspect
aspect
builder
	name:lonelyPerson
	class:com.chuan.simple.bean.example.basic.bean.aspect.LonelyPerson
	executable-parameter
		executable-name:defeat
		index:1
		val:loneliness
	executable-parameter
		executable-name:defeat
		index:1
		val:fear
	executable-parameter
		executable-name:defeat
		index:2
		val:hardship
	executable-parameter
		executable-name:defeat
		index:1
		val:pain
	executable-parameter
		executable-name:defeat
		index:2
		val:millstone
	executable-parameter
		executable-name:defeat
		index:3
		val:everything

